/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MisPersonajesRouteImport } from './routes/mis-personajes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomebrewRouteImport } from './routes/homebrew'
import { Route as CreacionRouteImport } from './routes/creacion'
import { Route as CompendioRouteImport } from './routes/compendio'
import { Route as CampanaRouteImport } from './routes/campana'
import { Route as IndexRouteImport } from './routes/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MisPersonajesRoute = MisPersonajesRouteImport.update({
  id: '/mis-personajes',
  path: '/mis-personajes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomebrewRoute = HomebrewRouteImport.update({
  id: '/homebrew',
  path: '/homebrew',
  getParentRoute: () => rootRouteImport,
} as any)
const CreacionRoute = CreacionRouteImport.update({
  id: '/creacion',
  path: '/creacion',
  getParentRoute: () => rootRouteImport,
} as any)
const CompendioRoute = CompendioRouteImport.update({
  id: '/compendio',
  path: '/compendio',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanaRoute = CampanaRouteImport.update({
  id: '/campana',
  path: '/campana',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campana': typeof CampanaRoute
  '/compendio': typeof CompendioRoute
  '/creacion': typeof CreacionRoute
  '/homebrew': typeof HomebrewRoute
  '/login': typeof LoginRoute
  '/mis-personajes': typeof MisPersonajesRoute
  '/register': typeof RegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campana': typeof CampanaRoute
  '/compendio': typeof CompendioRoute
  '/creacion': typeof CreacionRoute
  '/homebrew': typeof HomebrewRoute
  '/login': typeof LoginRoute
  '/mis-personajes': typeof MisPersonajesRoute
  '/register': typeof RegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campana': typeof CampanaRoute
  '/compendio': typeof CompendioRoute
  '/creacion': typeof CreacionRoute
  '/homebrew': typeof HomebrewRoute
  '/login': typeof LoginRoute
  '/mis-personajes': typeof MisPersonajesRoute
  '/register': typeof RegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campana'
    | '/compendio'
    | '/creacion'
    | '/homebrew'
    | '/login'
    | '/mis-personajes'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campana'
    | '/compendio'
    | '/creacion'
    | '/homebrew'
    | '/login'
    | '/mis-personajes'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/campana'
    | '/compendio'
    | '/creacion'
    | '/homebrew'
    | '/login'
    | '/mis-personajes'
    | '/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampanaRoute: typeof CampanaRoute
  CompendioRoute: typeof CompendioRoute
  CreacionRoute: typeof CreacionRoute
  HomebrewRoute: typeof HomebrewRoute
  LoginRoute: typeof LoginRoute
  MisPersonajesRoute: typeof MisPersonajesRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-personajes': {
      id: '/mis-personajes'
      path: '/mis-personajes'
      fullPath: '/mis-personajes'
      preLoaderRoute: typeof MisPersonajesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homebrew': {
      id: '/homebrew'
      path: '/homebrew'
      fullPath: '/homebrew'
      preLoaderRoute: typeof HomebrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creacion': {
      id: '/creacion'
      path: '/creacion'
      fullPath: '/creacion'
      preLoaderRoute: typeof CreacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compendio': {
      id: '/compendio'
      path: '/compendio'
      fullPath: '/compendio'
      preLoaderRoute: typeof CompendioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campana': {
      id: '/campana'
      path: '/campana'
      fullPath: '/campana'
      preLoaderRoute: typeof CampanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampanaRoute: CampanaRoute,
  CompendioRoute: CompendioRoute,
  CreacionRoute: CreacionRoute,
  HomebrewRoute: HomebrewRoute,
  LoginRoute: LoginRoute,
  MisPersonajesRoute: MisPersonajesRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
